name = "XAMAuxData"
uuid = "e99d641e-1821-45d7-9150-ecb7bf333fe1"
version = "0.1.0"
authors = ["Jakob Nybo Nissen <jakobnybonissen@gmail.com>"]

[deps]
MemViews = "a791c907-b98b-4e44-8f4d-e4c2362c6b2f"
StringViews = "354b36f9-a18e-4713-926e-db85100087ba"

[compat]
FormatSpecimens = "1.1.0"
MemViews = "0.2"
StringViews = "1.3.3"

[extras]
FormatSpecimens = "3372ea36-2a1a-11e9-3eb7-996970b6ffbd"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "FormatSpecimens"]
